package main

import (
	"fmt"

	"github.com/shafiqaimanx/warnax/colors"
	"github.com/shafiqaimanx/warnax/show"
)

func main() {
	
	fmt.Printf("\t\t[ALL THE STANDARD INDICATORS]\t\n\n")
	show.StandardIndicators()

	fmt.Printf("\t\t[ALL THE BOLD INDICATORS]\t\n\n")
	show.BoldIndicators()

	fmt.Printf("\t\t[ALL THE COLORS]\t\n\n")
	fmt.Printf("%sINDIANRED\n", colors.INDIANRED)
	fmt.Printf("%sLIGHTCORAL\n", colors.LIGHTCORAL)
	fmt.Printf("%sSALMON\n", colors.SALMON)
	fmt.Printf("%sDARKSALMON\n", colors.DARKSALMON)
	fmt.Printf("%sLIGHTSALMON\n", colors.LIGHTSALMON)
	fmt.Printf("%sCRIMSON\n", colors.CRIMSON)
	fmt.Printf("%sRED\n", colors.RED)
	fmt.Printf("%sFIREBRICK\n", colors.FIREBRICK)
	fmt.Printf("%sDARKRED\n", colors.DARKRED)
	fmt.Printf("%sPINK\n", colors.PINK)
	fmt.Printf("%sLIGHTPINK\n", colors.LIGHTPINK)
	fmt.Printf("%sHOTPINK\n", colors.HOTPINK)
	fmt.Printf("%sDEEPPINK\n", colors.DEEPPINK)
	fmt.Printf("%sMEDIUMVIOLETRED\n", colors.MEDIUMVIOLETRED)
	fmt.Printf("%sPALEVIOLETRED\n", colors.PALEVIOLETRED)
	fmt.Printf("%sCORAL\n", colors.CORAL)
	fmt.Printf("%sTOMATO\n", colors.TOMATO)
	fmt.Printf("%sORANGERED\n", colors.ORANGERED)
	fmt.Printf("%sDARKORANGE\n", colors.DARKORANGE)
	fmt.Printf("%sORANGE\n", colors.ORANGE)
	fmt.Printf("%sGOLD\n", colors.GOLD)
	fmt.Printf("%sYELLOW\n", colors.YELLOW)
	fmt.Printf("%sLIGHTYELLOW\n", colors.LIGHTYELLOW)
	fmt.Printf("%sLEMONCHIFFON\n", colors.LEMONCHIFFON)
	fmt.Printf("%sLIGHTGOLDENRODYELLOW\n", colors.LIGHTGOLDENRODYELLOW)
	fmt.Printf("%sPAPAYAWHIP\n", colors.PAPAYAWHIP)
	fmt.Printf("%sMOCCASIN\n", colors.MOCCASIN)
	fmt.Printf("%sPEACHPUFF\n", colors.PEACHPUFF)
	fmt.Printf("%sPALEGOLDENROD\n", colors.PALEGOLDENROD)
	fmt.Printf("%sKHAKI\n", colors.KHAKI)
	fmt.Printf("%sDARKKHAKI\n", colors.DARKKHAKI)
	fmt.Printf("%sLAVENDER\n", colors.LAVENDER)
	fmt.Printf("%sTHISTLE\n", colors.THISTLE)
	fmt.Printf("%sPLUM\n", colors.PLUM)
	fmt.Printf("%sVIOLET\n", colors.VIOLET)
	fmt.Printf("%sORCHID\n", colors.ORCHID)
	fmt.Printf("%sFUCHSIA\n", colors.FUCHSIA)
	fmt.Printf("%sMAGENTA\n", colors.MAGENTA)
	fmt.Printf("%sMEDIUMORCHID\n", colors.MEDIUMORCHID)
	fmt.Printf("%sMEDIUMPURPLE\n", colors.MEDIUMPURPLE)
	fmt.Printf("%sBLUEVIOLET\n", colors.BLUEVIOLET)
	fmt.Printf("%sDARKVIOLET\n", colors.DARKVIOLET)
	fmt.Printf("%sDARKORCHID\n", colors.DARKORCHID)
	fmt.Printf("%sDARKMAGENTA\n", colors.DARKMAGENTA)
	fmt.Printf("%sPURPLE\n", colors.PURPLE)
	fmt.Printf("%sINDIGO\n", colors.INDIGO)
	fmt.Printf("%sSLATEBLUE\n", colors.SLATEBLUE)
	fmt.Printf("%sDARKSLATEBLUE\n", colors.DARKSLATEBLUE)
	fmt.Printf("%sMEDIUMSLATEBLUE\n", colors.MEDIUMSLATEBLUE)
	fmt.Printf("%sGREENYELLOW\n", colors.GREENYELLOW)
	fmt.Printf("%sCHARTREUSE\n", colors.CHARTREUSE)
	fmt.Printf("%sLAWNGREEN\n", colors.LAWNGREEN)
	fmt.Printf("%sLIME\n", colors.LIME)
	fmt.Printf("%sLIMEGREEN\n", colors.LIMEGREEN)
	fmt.Printf("%sPALEGREEN\n", colors.PALEGREEN)
	fmt.Printf("%sLIGHTGREEN\n", colors.LIGHTGREEN)
	fmt.Printf("%sMEDIUMSPRINGGREEN\n", colors.MEDIUMSPRINGGREEN)
	fmt.Printf("%sSPRINGGREEN\n", colors.SPRINGGREEN)
	fmt.Printf("%sMEDIUMSEAGREEN\n", colors.MEDIUMSEAGREEN)
	fmt.Printf("%sSEAGREEN\n", colors.SEAGREEN)
	fmt.Printf("%sFORESTGREEN\n", colors.FORESTGREEN)
	fmt.Printf("%sGREEN\n", colors.GREEN)
	fmt.Printf("%sDARKGREEN\n", colors.DARKGREEN)
	fmt.Printf("%sYELLOWGREEN\n", colors.YELLOWGREEN)
	fmt.Printf("%sOLIVEDRAB\n", colors.OLIVEDRAB)
	fmt.Printf("%sOLIVE\n", colors.OLIVE)
	fmt.Printf("%sDARKOLIVEGREEN\n", colors.DARKOLIVEGREEN)
	fmt.Printf("%sMEDIUMAQUAMARINE\n", colors.MEDIUMAQUAMARINE)
	fmt.Printf("%sDARKSEAGREEN\n", colors.DARKSEAGREEN)
	fmt.Printf("%sLIGHTSEAGREEN\n", colors.LIGHTSEAGREEN)
	fmt.Printf("%sDARKCYAN\n", colors.DARKCYAN)
	fmt.Printf("%sTEAL\n", colors.TEAL)
	fmt.Printf("%sAQUA\n", colors.AQUA)
	fmt.Printf("%sCYAN\n", colors.CYAN)
	fmt.Printf("%sLIGHTCYAN\n", colors.LIGHTCYAN)
	fmt.Printf("%sPALETURQUOISE\n", colors.PALETURQUOISE)
	fmt.Printf("%sAQUAMARINE\n", colors.AQUAMARINE)
	fmt.Printf("%sTURQUOISE\n", colors.TURQUOISE)
	fmt.Printf("%sMEDIUMTURQUOISE\n", colors.MEDIUMTURQUOISE)
	fmt.Printf("%sDARKTURQUOISE\n", colors.DARKTURQUOISE)
	fmt.Printf("%sCADETBLUE\n", colors.CADETBLUE)
	fmt.Printf("%sSTEELBLUE\n", colors.STEELBLUE)
	fmt.Printf("%sLIGHTSTEELBLUE\n", colors.LIGHTSTEELBLUE)
	fmt.Printf("%sPOWDERBLUE\n", colors.POWDERBLUE)
	fmt.Printf("%sLIGHTBLUE\n", colors.LIGHTBLUE)
	fmt.Printf("%sSKYBLUE\n", colors.SKYBLUE)
	fmt.Printf("%sLIGHTSKYBLUE\n", colors.LIGHTSKYBLUE)
	fmt.Printf("%sDEEPSKYBLUE\n", colors.DEEPSKYBLUE)
	fmt.Printf("%sDODGERBLUE\n", colors.DODGERBLUE)
	fmt.Printf("%sCORNFLOWERBLUE\n", colors.CORNFLOWERBLUE)
	fmt.Printf("%sROYALBLUE\n", colors.ROYALBLUE)
	fmt.Printf("%sBLUE\n", colors.BLUE)
	fmt.Printf("%sMEDIUMBLUE\n", colors.MEDIUMBLUE)
	fmt.Printf("%sDARKBLUE\n", colors.DARKBLUE)
	fmt.Printf("%sNAVY\n", colors.NAVY)
	fmt.Printf("%sMIDNIGHTBLUE\n", colors.MIDNIGHTBLUE)
	fmt.Printf("%sCORNSILK\n", colors.CORNSILK)
	fmt.Printf("%sBLANCHEDALMOND\n", colors.BLANCHEDALMOND)
	fmt.Printf("%sBISQUE\n", colors.BISQUE)
	fmt.Printf("%sNAVAJOWHITE\n", colors.NAVAJOWHITE)
	fmt.Printf("%sWHEAT\n", colors.WHEAT)
	fmt.Printf("%sBURLYWOOD\n", colors.BURLYWOOD)
	fmt.Printf("%sTAN\n", colors.TAN)
	fmt.Printf("%sROSYBROWN\n", colors.ROSYBROWN)
	fmt.Printf("%sSANDYBROWN\n", colors.SANDYBROWN)
	fmt.Printf("%sGOLDENROD\n", colors.GOLDENROD)
	fmt.Printf("%sDARKGOLDENROD\n", colors.DARKGOLDENROD)
	fmt.Printf("%sPERU\n", colors.PERU)
	fmt.Printf("%sCHOCOLATE\n", colors.CHOCOLATE)
	fmt.Printf("%sSADDLEBROWN\n", colors.SADDLEBROWN)
	fmt.Printf("%sSIENNA\n", colors.SIENNA)
	fmt.Printf("%sBROWN\n", colors.BROWN)
	fmt.Printf("%sMAROON\n", colors.MAROON)
	fmt.Printf("%sWHITE\n", colors.WHITE)
	fmt.Printf("%sSNOW\n", colors.SNOW)
	fmt.Printf("%sHONEYDEW\n", colors.HONEYDEW)
	fmt.Printf("%sMINTCREAM\n", colors.MINTCREAM)
	fmt.Printf("%sAZURE\n", colors.AZURE)
	fmt.Printf("%sALICEBLUE\n", colors.ALICEBLUE)
	fmt.Printf("%sGHOSTWHITE\n", colors.GHOSTWHITE)
	fmt.Printf("%sWHITESMOKE\n", colors.WHITESMOKE)
	fmt.Printf("%sSEASHELL\n", colors.SEASHELL)
	fmt.Printf("%sBEIGE\n", colors.BEIGE)
	fmt.Printf("%sOLDLACE\n", colors.OLDLACE)
	fmt.Printf("%sFLORALWHITE\n", colors.FLORALWHITE)
	fmt.Printf("%sIVORY\n", colors.IVORY)
	fmt.Printf("%sANTIQUEWHITE\n", colors.ANTIQUEWHITE)
	fmt.Printf("%sLINEN\n", colors.LINEN)
	fmt.Printf("%sLAVENDERBLUSH\n", colors.LAVENDERBLUSH)
	fmt.Printf("%sMISTYROSE\n", colors.MISTYROSE)
	fmt.Printf("%sGAINSBORO\n", colors.GAINSBORO)
	fmt.Printf("%sLIGHTGREY\n", colors.LIGHTGREY)
	fmt.Printf("%sSILVER\n", colors.SILVER)
	fmt.Printf("%sDARKGRAY\n", colors.DARKGRAY)
	fmt.Printf("%sGRAY\n", colors.GRAY)
	fmt.Printf("%sDIMGRAY\n", colors.DIMGRAY)
	fmt.Printf("%sLIGHTSLATEGRAY\n", colors.LIGHTSLATEGRAY)
	fmt.Printf("%sSLATEGRAY\n", colors.SLATEGRAY)
	fmt.Printf("%sDARKSLATEGRAY\n", colors.DARKSLATEGRAY)
	fmt.Printf("%sBLACK\n", colors.BLACK)
}
