package main

import (
	"fmt"

	"github.com/shafiqaimanx/warnax/colors"
	"github.com/shafiqaimanx/warnax/show"
)

func main() {
	
	fmt.Printf("\t\t[ALL THE STANDARD INDICATORS]\t\n\n")
	show.StandardIndicators()

	fmt.Printf("\t\t[ALL THE BOLD INDICATORS]\t\n\n")
	show.BoldIndicators()

	fmt.Printf("\t\t[ALL THE FOREGROUND COLORS]\t\n\n")
	fmt.Printf("%sINDIANRED\n", colors.INDIANRED)
	fmt.Printf("%sLIGHTCORAL\n", colors.LIGHTCORAL)
	fmt.Printf("%sSALMON\n", colors.SALMON)
	fmt.Printf("%sDARKSALMON\n", colors.DARKSALMON)
	fmt.Printf("%sLIGHTSALMON\n", colors.LIGHTSALMON)
	fmt.Printf("%sCRIMSON\n", colors.CRIMSON)
	fmt.Printf("%sRED\n", colors.RED)
	fmt.Printf("%sFIREBRICK\n", colors.FIREBRICK)
	fmt.Printf("%sDARKRED\n", colors.DARKRED)
	fmt.Printf("%sPINK\n", colors.PINK)
	fmt.Printf("%sLIGHTPINK\n", colors.LIGHTPINK)
	fmt.Printf("%sHOTPINK\n", colors.HOTPINK)
	fmt.Printf("%sDEEPPINK\n", colors.DEEPPINK)
	fmt.Printf("%sMEDIUMVIOLETRED\n", colors.MEDIUMVIOLETRED)
	fmt.Printf("%sPALEVIOLETRED\n", colors.PALEVIOLETRED)
	fmt.Printf("%sCORAL\n", colors.CORAL)
	fmt.Printf("%sTOMATO\n", colors.TOMATO)
	fmt.Printf("%sORANGERED\n", colors.ORANGERED)
	fmt.Printf("%sDARKORANGE\n", colors.DARKORANGE)
	fmt.Printf("%sORANGE\n", colors.ORANGE)
	fmt.Printf("%sGOLD\n", colors.GOLD)
	fmt.Printf("%sYELLOW\n", colors.YELLOW)
	fmt.Printf("%sLIGHTYELLOW\n", colors.LIGHTYELLOW)
	fmt.Printf("%sLEMONCHIFFON\n", colors.LEMONCHIFFON)
	fmt.Printf("%sLIGHTGOLDENRODYELLOW\n", colors.LIGHTGOLDENRODYELLOW)
	fmt.Printf("%sPAPAYAWHIP\n", colors.PAPAYAWHIP)
	fmt.Printf("%sMOCCASIN\n", colors.MOCCASIN)
	fmt.Printf("%sPEACHPUFF\n", colors.PEACHPUFF)
	fmt.Printf("%sPALEGOLDENROD\n", colors.PALEGOLDENROD)
	fmt.Printf("%sKHAKI\n", colors.KHAKI)
	fmt.Printf("%sDARKKHAKI\n", colors.DARKKHAKI)
	fmt.Printf("%sLAVENDER\n", colors.LAVENDER)
	fmt.Printf("%sTHISTLE\n", colors.THISTLE)
	fmt.Printf("%sPLUM\n", colors.PLUM)
	fmt.Printf("%sVIOLET\n", colors.VIOLET)
	fmt.Printf("%sORCHID\n", colors.ORCHID)
	fmt.Printf("%sFUCHSIA\n", colors.FUCHSIA)
	fmt.Printf("%sMAGENTA\n", colors.MAGENTA)
	fmt.Printf("%sMEDIUMORCHID\n", colors.MEDIUMORCHID)
	fmt.Printf("%sMEDIUMPURPLE\n", colors.MEDIUMPURPLE)
	fmt.Printf("%sBLUEVIOLET\n", colors.BLUEVIOLET)
	fmt.Printf("%sDARKVIOLET\n", colors.DARKVIOLET)
	fmt.Printf("%sDARKORCHID\n", colors.DARKORCHID)
	fmt.Printf("%sDARKMAGENTA\n", colors.DARKMAGENTA)
	fmt.Printf("%sPURPLE\n", colors.PURPLE)
	fmt.Printf("%sINDIGO\n", colors.INDIGO)
	fmt.Printf("%sSLATEBLUE\n", colors.SLATEBLUE)
	fmt.Printf("%sDARKSLATEBLUE\n", colors.DARKSLATEBLUE)
	fmt.Printf("%sMEDIUMSLATEBLUE\n", colors.MEDIUMSLATEBLUE)
	fmt.Printf("%sGREENYELLOW\n", colors.GREENYELLOW)
	fmt.Printf("%sCHARTREUSE\n", colors.CHARTREUSE)
	fmt.Printf("%sLAWNGREEN\n", colors.LAWNGREEN)
	fmt.Printf("%sLIME\n", colors.LIME)
	fmt.Printf("%sLIMEGREEN\n", colors.LIMEGREEN)
	fmt.Printf("%sPALEGREEN\n", colors.PALEGREEN)
	fmt.Printf("%sLIGHTGREEN\n", colors.LIGHTGREEN)
	fmt.Printf("%sMEDIUMSPRINGGREEN\n", colors.MEDIUMSPRINGGREEN)
	fmt.Printf("%sSPRINGGREEN\n", colors.SPRINGGREEN)
	fmt.Printf("%sMEDIUMSEAGREEN\n", colors.MEDIUMSEAGREEN)
	fmt.Printf("%sSEAGREEN\n", colors.SEAGREEN)
	fmt.Printf("%sFORESTGREEN\n", colors.FORESTGREEN)
	fmt.Printf("%sGREEN\n", colors.GREEN)
	fmt.Printf("%sDARKGREEN\n", colors.DARKGREEN)
	fmt.Printf("%sYELLOWGREEN\n", colors.YELLOWGREEN)
	fmt.Printf("%sOLIVEDRAB\n", colors.OLIVEDRAB)
	fmt.Printf("%sOLIVE\n", colors.OLIVE)
	fmt.Printf("%sDARKOLIVEGREEN\n", colors.DARKOLIVEGREEN)
	fmt.Printf("%sMEDIUMAQUAMARINE\n", colors.MEDIUMAQUAMARINE)
	fmt.Printf("%sDARKSEAGREEN\n", colors.DARKSEAGREEN)
	fmt.Printf("%sLIGHTSEAGREEN\n", colors.LIGHTSEAGREEN)
	fmt.Printf("%sDARKCYAN\n", colors.DARKCYAN)
	fmt.Printf("%sTEAL\n", colors.TEAL)
	fmt.Printf("%sAQUA\n", colors.AQUA)
	fmt.Printf("%sCYAN\n", colors.CYAN)
	fmt.Printf("%sLIGHTCYAN\n", colors.LIGHTCYAN)
	fmt.Printf("%sPALETURQUOISE\n", colors.PALETURQUOISE)
	fmt.Printf("%sAQUAMARINE\n", colors.AQUAMARINE)
	fmt.Printf("%sTURQUOISE\n", colors.TURQUOISE)
	fmt.Printf("%sMEDIUMTURQUOISE\n", colors.MEDIUMTURQUOISE)
	fmt.Printf("%sDARKTURQUOISE\n", colors.DARKTURQUOISE)
	fmt.Printf("%sCADETBLUE\n", colors.CADETBLUE)
	fmt.Printf("%sSTEELBLUE\n", colors.STEELBLUE)
	fmt.Printf("%sLIGHTSTEELBLUE\n", colors.LIGHTSTEELBLUE)
	fmt.Printf("%sPOWDERBLUE\n", colors.POWDERBLUE)
	fmt.Printf("%sLIGHTBLUE\n", colors.LIGHTBLUE)
	fmt.Printf("%sSKYBLUE\n", colors.SKYBLUE)
	fmt.Printf("%sLIGHTSKYBLUE\n", colors.LIGHTSKYBLUE)
	fmt.Printf("%sDEEPSKYBLUE\n", colors.DEEPSKYBLUE)
	fmt.Printf("%sDODGERBLUE\n", colors.DODGERBLUE)
	fmt.Printf("%sCORNFLOWERBLUE\n", colors.CORNFLOWERBLUE)
	fmt.Printf("%sROYALBLUE\n", colors.ROYALBLUE)
	fmt.Printf("%sBLUE\n", colors.BLUE)
	fmt.Printf("%sMEDIUMBLUE\n", colors.MEDIUMBLUE)
	fmt.Printf("%sDARKBLUE\n", colors.DARKBLUE)
	fmt.Printf("%sNAVY\n", colors.NAVY)
	fmt.Printf("%sMIDNIGHTBLUE\n", colors.MIDNIGHTBLUE)
	fmt.Printf("%sCORNSILK\n", colors.CORNSILK)
	fmt.Printf("%sBLANCHEDALMOND\n", colors.BLANCHEDALMOND)
	fmt.Printf("%sBISQUE\n", colors.BISQUE)
	fmt.Printf("%sNAVAJOWHITE\n", colors.NAVAJOWHITE)
	fmt.Printf("%sWHEAT\n", colors.WHEAT)
	fmt.Printf("%sBURLYWOOD\n", colors.BURLYWOOD)
	fmt.Printf("%sTAN\n", colors.TAN)
	fmt.Printf("%sROSYBROWN\n", colors.ROSYBROWN)
	fmt.Printf("%sSANDYBROWN\n", colors.SANDYBROWN)
	fmt.Printf("%sGOLDENROD\n", colors.GOLDENROD)
	fmt.Printf("%sDARKGOLDENROD\n", colors.DARKGOLDENROD)
	fmt.Printf("%sPERU\n", colors.PERU)
	fmt.Printf("%sCHOCOLATE\n", colors.CHOCOLATE)
	fmt.Printf("%sSADDLEBROWN\n", colors.SADDLEBROWN)
	fmt.Printf("%sSIENNA\n", colors.SIENNA)
	fmt.Printf("%sBROWN\n", colors.BROWN)
	fmt.Printf("%sMAROON\n", colors.MAROON)
	fmt.Printf("%sWHITE\n", colors.WHITE)
	fmt.Printf("%sSNOW\n", colors.SNOW)
	fmt.Printf("%sHONEYDEW\n", colors.HONEYDEW)
	fmt.Printf("%sMINTCREAM\n", colors.MINTCREAM)
	fmt.Printf("%sAZURE\n", colors.AZURE)
	fmt.Printf("%sALICEBLUE\n", colors.ALICEBLUE)
	fmt.Printf("%sGHOSTWHITE\n", colors.GHOSTWHITE)
	fmt.Printf("%sWHITESMOKE\n", colors.WHITESMOKE)
	fmt.Printf("%sSEASHELL\n", colors.SEASHELL)
	fmt.Printf("%sBEIGE\n", colors.BEIGE)
	fmt.Printf("%sOLDLACE\n", colors.OLDLACE)
	fmt.Printf("%sFLORALWHITE\n", colors.FLORALWHITE)
	fmt.Printf("%sIVORY\n", colors.IVORY)
	fmt.Printf("%sANTIQUEWHITE\n", colors.ANTIQUEWHITE)
	fmt.Printf("%sLINEN\n", colors.LINEN)
	fmt.Printf("%sLAVENDERBLUSH\n", colors.LAVENDERBLUSH)
	fmt.Printf("%sMISTYROSE\n", colors.MISTYROSE)
	fmt.Printf("%sGAINSBORO\n", colors.GAINSBORO)
	fmt.Printf("%sLIGHTGREY\n", colors.LIGHTGREY)
	fmt.Printf("%sSILVER\n", colors.SILVER)
	fmt.Printf("%sDARKGRAY\n", colors.DARKGRAY)
	fmt.Printf("%sGRAY\n", colors.GRAY)
	fmt.Printf("%sDIMGRAY\n", colors.DIMGRAY)
	fmt.Printf("%sLIGHTSLATEGRAY\n", colors.LIGHTSLATEGRAY)
	fmt.Printf("%sSLATEGRAY\n", colors.SLATEGRAY)
	fmt.Printf("%sDARKSLATEGRAY\n", colors.DARKSLATEGRAY)
	fmt.Printf("%sBLACK%s\n", colors.BLACK, colors.RESET)

	fmt.Println("")

	fmt.Printf("\t\t[ALL THE BACKGROUND COLORS]\t\n\n")
	fmt.Printf("%sINDIANRED%s\n", colors.INDIANRED_BG, colors.RESET)
    fmt.Printf("%sLIGHTCORAL%s\n", colors.LIGHTCORAL_BG, colors.RESET)
    fmt.Printf("%sSALMON%s\n", colors.SALMON_BG, colors.RESET)
    fmt.Printf("%sDARKSALMON%s\n", colors.DARKSALMON_BG, colors.RESET)
    fmt.Printf("%sLIGHTSALMON%s\n", colors.LIGHTSALMON_BG, colors.RESET)
    fmt.Printf("%sCRIMSON%s\n", colors.CRIMSON_BG, colors.RESET)
    fmt.Printf("%sRED%s\n", colors.RED_BG, colors.RESET)
    fmt.Printf("%sFIREBRICK%s\n", colors.FIREBRICK_BG, colors.RESET)
    fmt.Printf("%sDARKRED%s\n", colors.DARKRED_BG, colors.RESET)
    fmt.Printf("%sPINK%s\n", colors.PINK_BG, colors.RESET)
    fmt.Printf("%sLIGHTPINK%s\n", colors.LIGHTPINK_BG, colors.RESET)
    fmt.Printf("%sHOTPINK%s\n", colors.HOTPINK_BG, colors.RESET)
    fmt.Printf("%sDEEPPINK%s\n", colors.DEEPPINK_BG, colors.RESET)
    fmt.Printf("%sMEDIUMVIOLETRED%s\n", colors.MEDIUMVIOLETRED_BG, colors.RESET)
    fmt.Printf("%sPALEVIOLETRED%s\n", colors.PALEVIOLETRED_BG, colors.RESET)
    fmt.Printf("%sCORAL%s\n", colors.CORAL_BG, colors.RESET)
    fmt.Printf("%sTOMATO%s\n", colors.TOMATO_BG, colors.RESET)
    fmt.Printf("%sORANGERED%s\n", colors.ORANGERED_BG, colors.RESET)
    fmt.Printf("%sDARKORANGE%s\n", colors.DARKORANGE_BG, colors.RESET)
    fmt.Printf("%sORANGE%s\n", colors.ORANGE_BG, colors.RESET)
    fmt.Printf("%sGOLD%s\n", colors.GOLD_BG, colors.RESET)
    fmt.Printf("%sYELLOW%s\n", colors.YELLOW_BG, colors.RESET)
    fmt.Printf("%sLIGHTYELLOW%s\n", colors.LIGHTYELLOW_BG, colors.RESET)
    fmt.Printf("%sLEMONCHIFFON%s\n", colors.LEMONCHIFFON_BG, colors.RESET)
    fmt.Printf("%sLIGHTGOLDENRODYELLOW%s\n", colors.LIGHTGOLDENRODYELLOW_BG, colors.RESET)
    fmt.Printf("%sPAPAYAWHIP%s\n", colors.PAPAYAWHIP_BG, colors.RESET)
    fmt.Printf("%sMOCCASIN%s\n", colors.MOCCASIN_BG, colors.RESET)
    fmt.Printf("%sPEACHPUFF%s\n", colors.PEACHPUFF_BG, colors.RESET)
    fmt.Printf("%sPALEGOLDENROD%s\n", colors.PALEGOLDENROD_BG, colors.RESET)
    fmt.Printf("%sKHAKI%s\n", colors.KHAKI_BG, colors.RESET)
    fmt.Printf("%sDARKKHAKI%s\n", colors.DARKKHAKI_BG, colors.RESET)
    fmt.Printf("%sLAVENDER%s\n", colors.LAVENDER_BG, colors.RESET)
    fmt.Printf("%sTHISTLE%s\n", colors.THISTLE_BG, colors.RESET)
    fmt.Printf("%sPLUM%s\n", colors.PLUM_BG, colors.RESET)
    fmt.Printf("%sVIOLET%s\n", colors.VIOLET_BG, colors.RESET)
    fmt.Printf("%sORCHID%s\n", colors.ORCHID_BG, colors.RESET)
    fmt.Printf("%sFUCHSIA%s\n", colors.FUCHSIA_BG, colors.RESET)
    fmt.Printf("%sMAGENTA%s\n", colors.MAGENTA_BG, colors.RESET)
    fmt.Printf("%sMEDIUMORCHID%s\n", colors.MEDIUMORCHID_BG, colors.RESET)
    fmt.Printf("%sMEDIUMPURPLE%s\n", colors.MEDIUMPURPLE_BG, colors.RESET)
    fmt.Printf("%sBLUEVIOLET%s\n", colors.BLUEVIOLET_BG, colors.RESET)
    fmt.Printf("%sDARKVIOLET%s\n", colors.DARKVIOLET_BG, colors.RESET)
    fmt.Printf("%sDARKORCHID%s\n", colors.DARKORCHID_BG, colors.RESET)
    fmt.Printf("%sDARKMAGENTA%s\n", colors.DARKMAGENTA_BG, colors.RESET)
    fmt.Printf("%sPURPLE%s\n", colors.PURPLE_BG, colors.RESET)
    fmt.Printf("%sINDIGO%s\n", colors.INDIGO_BG, colors.RESET)
    fmt.Printf("%sSLATEBLUE%s\n", colors.SLATEBLUE_BG, colors.RESET)
    fmt.Printf("%sDARKSLATEBLUE%s\n", colors.DARKSLATEBLUE_BG, colors.RESET)
    fmt.Printf("%sMEDIUMSLATEBLUE%s\n", colors.MEDIUMSLATEBLUE_BG, colors.RESET)
    fmt.Printf("%sGREENYELLOW%s\n", colors.GREENYELLOW_BG, colors.RESET)
    fmt.Printf("%sCHARTREUSE%s\n", colors.CHARTREUSE_BG, colors.RESET)
    fmt.Printf("%sLAWNGREEN%s\n", colors.LAWNGREEN_BG, colors.RESET)
    fmt.Printf("%sLIME%s\n", colors.LIME_BG, colors.RESET)
    fmt.Printf("%sLIMEGREEN%s\n", colors.LIMEGREEN_BG, colors.RESET)
    fmt.Printf("%sPALEGREEN%s\n", colors.PALEGREEN_BG, colors.RESET)
    fmt.Printf("%sLIGHTGREEN%s\n", colors.LIGHTGREEN_BG, colors.RESET)
    fmt.Printf("%sMEDIUMSPRINGGREEN%s\n", colors.MEDIUMSPRINGGREEN_BG, colors.RESET)
    fmt.Printf("%sSPRINGGREEN%s\n", colors.SPRINGGREEN_BG, colors.RESET)
    fmt.Printf("%sMEDIUMSEAGREEN%s\n", colors.MEDIUMSEAGREEN_BG, colors.RESET)
    fmt.Printf("%sSEAGREEN%s\n", colors.SEAGREEN_BG, colors.RESET)
    fmt.Printf("%sFORESTGREEN%s\n", colors.FORESTGREEN_BG, colors.RESET)
    fmt.Printf("%sGREEN%s\n", colors.GREEN_BG, colors.RESET)
    fmt.Printf("%sDARKGREEN%s\n", colors.DARKGREEN_BG, colors.RESET)
    fmt.Printf("%sYELLOWGREEN%s\n", colors.YELLOWGREEN_BG, colors.RESET)
    fmt.Printf("%sOLIVEDRAB%s\n", colors.OLIVEDRAB_BG, colors.RESET)
    fmt.Printf("%sOLIVE%s\n", colors.OLIVE_BG, colors.RESET)
    fmt.Printf("%sDARKOLIVEGREEN%s\n", colors.DARKOLIVEGREEN_BG, colors.RESET)
    fmt.Printf("%sMEDIUMAQUAMARINE%s\n", colors.MEDIUMAQUAMARINE_BG, colors.RESET)
    fmt.Printf("%sDARKSEAGREEN%s\n", colors.DARKSEAGREEN_BG, colors.RESET)
    fmt.Printf("%sLIGHTSEAGREEN%s\n", colors.LIGHTSEAGREEN_BG, colors.RESET)
    fmt.Printf("%sDARKCYAN%s\n", colors.DARKCYAN_BG, colors.RESET)
    fmt.Printf("%sTEAL%s\n", colors.TEAL_BG, colors.RESET)
    fmt.Printf("%sAQUA%s\n", colors.AQUA_BG, colors.RESET)
    fmt.Printf("%sCYAN%s\n", colors.CYAN_BG, colors.RESET)
    fmt.Printf("%sLIGHTCYAN%s\n", colors.LIGHTCYAN_BG, colors.RESET)
    fmt.Printf("%sPALETURQUOISE%s\n", colors.PALETURQUOISE_BG, colors.RESET)
    fmt.Printf("%sAQUAMARINE%s\n", colors.AQUAMARINE_BG, colors.RESET)
    fmt.Printf("%sTURQUOISE%s\n", colors.TURQUOISE_BG, colors.RESET)
    fmt.Printf("%sMEDIUMTURQUOISE%s\n", colors.MEDIUMTURQUOISE_BG, colors.RESET)
    fmt.Printf("%sDARKTURQUOISE%s\n", colors.DARKTURQUOISE_BG, colors.RESET)
    fmt.Printf("%sCADETBLUE%s\n", colors.CADETBLUE_BG, colors.RESET)
    fmt.Printf("%sSTEELBLUE%s\n", colors.STEELBLUE_BG, colors.RESET)
    fmt.Printf("%sLIGHTSTEELBLUE%s\n", colors.LIGHTSTEELBLUE_BG, colors.RESET)
    fmt.Printf("%sPOWDERBLUE%s\n", colors.POWDERBLUE_BG, colors.RESET)
    fmt.Printf("%sLIGHTBLUE%s\n", colors.LIGHTBLUE_BG, colors.RESET)
    fmt.Printf("%sSKYBLUE%s\n", colors.SKYBLUE_BG, colors.RESET)
    fmt.Printf("%sLIGHTSKYBLUE%s\n", colors.LIGHTSKYBLUE_BG, colors.RESET)
    fmt.Printf("%sDEEPSKYBLUE%s\n", colors.DEEPSKYBLUE_BG, colors.RESET)
    fmt.Printf("%sDODGERBLUE%s\n", colors.DODGERBLUE_BG, colors.RESET)
    fmt.Printf("%sCORNFLOWERBLUE%s\n", colors.CORNFLOWERBLUE_BG, colors.RESET)
    fmt.Printf("%sROYALBLUE%s\n", colors.ROYALBLUE_BG, colors.RESET)
    fmt.Printf("%sBLUE%s\n", colors.BLUE_BG, colors.RESET)
    fmt.Printf("%sMEDIUMBLUE%s\n", colors.MEDIUMBLUE_BG, colors.RESET)
    fmt.Printf("%sDARKBLUE%s\n", colors.DARKBLUE_BG, colors.RESET)
    fmt.Printf("%sNAVY%s\n", colors.NAVY_BG, colors.RESET)
    fmt.Printf("%sMIDNIGHTBLUE%s\n", colors.MIDNIGHTBLUE_BG, colors.RESET)
    fmt.Printf("%sCORNSILK%s\n", colors.CORNSILK_BG, colors.RESET)
    fmt.Printf("%sBLANCHEDALMOND%s\n", colors.BLANCHEDALMOND_BG, colors.RESET)
    fmt.Printf("%sBISQUE%s\n", colors.BISQUE_BG, colors.RESET)
    fmt.Printf("%sNAVAJOWHITE%s\n", colors.NAVAJOWHITE_BG, colors.RESET)
    fmt.Printf("%sWHEAT%s\n", colors.WHEAT_BG, colors.RESET)
    fmt.Printf("%sBURLYWOOD%s\n", colors.BURLYWOOD_BG, colors.RESET)
    fmt.Printf("%sTAN%s\n", colors.TAN_BG, colors.RESET)
    fmt.Printf("%sROSYBROWN%s\n", colors.ROSYBROWN_BG, colors.RESET)
    fmt.Printf("%sSANDYBROWN%s\n", colors.SANDYBROWN_BG, colors.RESET)
    fmt.Printf("%sGOLDENROD%s\n", colors.GOLDENROD_BG, colors.RESET)
    fmt.Printf("%sDARKGOLDENROD%s\n", colors.DARKGOLDENROD_BG, colors.RESET)
    fmt.Printf("%sPERU%s\n", colors.PERU_BG, colors.RESET)
    fmt.Printf("%sCHOCOLATE%s\n", colors.CHOCOLATE_BG, colors.RESET)
    fmt.Printf("%sSADDLEBROWN%s\n", colors.SADDLEBROWN_BG, colors.RESET)
    fmt.Printf("%sSIENNA%s\n", colors.SIENNA_BG, colors.RESET)
    fmt.Printf("%sBROWN%s\n", colors.BROWN_BG, colors.RESET)
    fmt.Printf("%sMAROON%s\n", colors.MAROON_BG, colors.RESET)
    fmt.Printf("%sWHITE%s\n", colors.WHITE_BG, colors.RESET)
    fmt.Printf("%sSNOW%s\n", colors.SNOW_BG, colors.RESET)
    fmt.Printf("%sHONEYDEW%s\n", colors.HONEYDEW_BG, colors.RESET)
    fmt.Printf("%sMINTCREAM%s\n", colors.MINTCREAM_BG, colors.RESET)
    fmt.Printf("%sAZURE%s\n", colors.AZURE_BG, colors.RESET)
    fmt.Printf("%sALICEBLUE%s\n", colors.ALICEBLUE_BG, colors.RESET)
    fmt.Printf("%sGHOSTWHITE%s\n", colors.GHOSTWHITE_BG, colors.RESET)
    fmt.Printf("%sWHITESMOKE%s\n", colors.WHITESMOKE_BG, colors.RESET)
    fmt.Printf("%sSEASHELL%s\n", colors.SEASHELL_BG, colors.RESET)
    fmt.Printf("%sBEIGE%s\n", colors.BEIGE_BG, colors.RESET)
    fmt.Printf("%sOLDLACE%s\n", colors.OLDLACE_BG, colors.RESET)
    fmt.Printf("%sFLORALWHITE%s\n", colors.FLORALWHITE_BG, colors.RESET)
    fmt.Printf("%sIVORY%s\n", colors.IVORY_BG, colors.RESET)
    fmt.Printf("%sANTIQUEWHITE%s\n", colors.ANTIQUEWHITE_BG, colors.RESET)
    fmt.Printf("%sLINEN%s\n", colors.LINEN_BG, colors.RESET)
    fmt.Printf("%sLAVENDERBLUSH%s\n", colors.LAVENDERBLUSH_BG, colors.RESET)
    fmt.Printf("%sMISTYROSE%s\n", colors.MISTYROSE_BG, colors.RESET)
    fmt.Printf("%sGAINSBORO%s\n", colors.GAINSBORO_BG, colors.RESET)
    fmt.Printf("%sLIGHTGREY%s\n", colors.LIGHTGREY_BG, colors.RESET)
    fmt.Printf("%sSILVER%s\n", colors.SILVER_BG, colors.RESET)
    fmt.Printf("%sDARKGRAY%s\n", colors.DARKGRAY_BG, colors.RESET)
    fmt.Printf("%sGRAY%s\n", colors.GRAY_BG, colors.RESET)
    fmt.Printf("%sDIMGRAY%s\n", colors.DIMGRAY_BG, colors.RESET)
    fmt.Printf("%sLIGHTSLATEGRAY%s\n", colors.LIGHTSLATEGRAY_BG, colors.RESET)
    fmt.Printf("%sSLATEGRAY%s\n", colors.SLATEGRAY_BG, colors.RESET)
    fmt.Printf("%sDARKSLATEGRAY%s\n", colors.DARKSLATEGRAY_BG, colors.RESET)
    fmt.Printf("%sBLACK%s\n", colors.BLACK_BG, colors.RESET)
}
